name: Build and Deploy

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Build
        run: node build.js

      - name: Deploy to GitHub Pages
        if: github.ref == 'refs/heads/main'
        run: |
          touch build/.nojekyll
          git config --global user.name "${{ github.actor }}"
          git config --global user.email "${{ github.actor }}@users.noreply.github.com"
          git checkout --orphan gh-pages
          git rm -rf .
          cp -r build/* .
          cp build/.nojekyll .
          git add .
          git commit -m "Deploy to GitHub Pages"
          git push -f origin gh-pages